/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.harsh.rpssim;

import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;

/**
 *
 * @author Harsh Noise
 */
public class CreatureViewerPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreatureViewerPanel
     */
    
    private BufferedImage[] teamSprites = new BufferedImage[3];
    private Creature[] creatures;
    
    public CreatureViewerPanel() {
        try {
            teamSprites[0] = ImageIO.read(getClass().getResourceAsStream("/images/rock.png"));
            teamSprites[1] = ImageIO.read(getClass().getResourceAsStream("/images/paper.png"));
            teamSprites[2] = ImageIO.read(getClass().getResourceAsStream("/images/scissors.png"));
        } catch (IOException ex) {
            System.getLogger(CreatureViewerPanel.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            System.out.println("Error loading player sprites in jpanel");
        }
        initComponents();
    }
    
    public void updateCreatures(Creature[] newCreatures){
        creatures = newCreatures;
    }
    
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        
        if (creatures == null) {
            return;
        }
        for (Creature c : creatures) {
            g.drawImage(teamSprites[c.getTeam()], (int)c.getXCoords()-8, (int)c.getYCoords()-8, null);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 403, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 213, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
